# Generated by Django 4.1.7 on 2023-03-29 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cook",
            name="kitchen_process",
        ),
        migrations.RemoveField(
            model_name="dishtype",
            name="kitchen_process",
        ),
        migrations.DeleteModel(
            name="KitchenProcess",
        ),
    ]
