# Generated by Django 4.1.7 on 2023-05-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0003_alter_dish_cooks_alter_dish_dish_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
